package telemetry

import (
	"context"

	"github.com/MovieStoreGuy/homify/device"
)

type (
	// Provider allows for any telemetry type to accept statistics generated by the
	// runtime and report it back to configured telemetry system
	Provider interface {
		// CaptureStatistics reads an entire device list and then report
		// devices that provide statistics to the provided telemetry.
		CaptureStatistics(ctx context.Context, list device.List) error
		// Flush allows the provider to be periodically reset with any
		// buffers being held to be written to the underlying system.
		Flush(ctx context.Context) error
	}
)
